### ISSUE TITLE
Expose fromJson/toJson on models?

### ISSUE THREAD

**Issue by Akora-IngDKB** [Zfinix/data_usage#3]
The models are meant to be kind of read-only. The values come from the package and the user doesn't have to set or create.
Is it still okay to expose the `fromJson` constructor and `toJson` method?

**Comment by Zfinix** [comment]
I don't see a problem with giving that flexibility.

**Comment by Akora-IngDKB** [comment]
Okay.
I was thinking differently. 
But if need be, they can be mocked rather than manipulating it directly. 
@Zfinix do you think?

**Comment by Zfinix** [comment]
Yes
